// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel;
using Speed;
using Speed.Data;


namespace TestGen.MariaDB.Data
{

    [DbTable("Speed", "vwsale", "", "")]
    [Serializable]
    [DataContract(Name = "Vwsale", Namespace = "")]
//    [System.Diagnostics.DebuggerStepThrough]
    public partial class Vwsale : Record, ICloneable, INotifyPropertyChanged
    {

        private Int32 z_SaleId;
        [DbColumn("Sale_Id")]
        [DataMember]
        public Int32 SaleId
        {
            get { return z_SaleId; }
            set
            {
                if (z_SaleId != value)
                {
                    z_SaleId = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }

        private Int32 z_CustomerId;
        [DbColumn("Customer_Id")]
        [DataMember]
        public Int32 CustomerId
        {
            get { return z_CustomerId; }
            set
            {
                if (z_CustomerId != value)
                {
                    z_CustomerId = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }

        private String z_CustomerName;
        [DbColumn("Customer_Name")]
        [DataMember]
        public String CustomerName
        {
            get { return z_CustomerName; }
            set
            {
                if (z_CustomerName != value)
                {
                    z_CustomerName = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }

        
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region IsEqual

        public bool IsEqual(Vwsale value)
        {
            if (value == null)
                return false;
            return
				this.SaleId == value.SaleId &&
				this.CustomerId == value.CustomerId &&
				this.CustomerName == value.CustomerName;

        }

        #endregion IsEqual

        #region Clone

        public override object Clone()
        {
            return CloneT();
        }

        public Vwsale CloneT()
        {
            Vwsale value = new Vwsale();
            value.RecordStatus = this.RecordStatus;
            value.RecordTag = this.RecordTag;

			value.SaleId = this.SaleId;
			value.CustomerId = this.CustomerId;
			value.CustomerName = this.CustomerName;

            return value;
        }

        #endregion Clone

        #region Create

        public static Vwsale Create(Int32 _SaleId, Int32 _CustomerId, String _CustomerName)
        {
            Vwsale __value = new Vwsale();

			__value.SaleId = _SaleId;
			__value.CustomerId = _CustomerId;
			__value.CustomerName = _CustomerName;

            return __value;
        }

        #endregion Create

   }

}
