// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.MariaDB.Data;

namespace TestGen.MariaDB.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Sale : BLClass<TestGen.MariaDB.Data.Sale>
    {

        public static TestGen.MariaDB.Data.Sale SelectByPk(Database db, Int32 _SaleId)
        {
            return db.SelectSingle<TestGen.MariaDB.Data.Sale>(string.Format("Sale_Id={0}", _SaleId));
        }

        public static int DeleteByPk(Database db, Int32 _SaleId)
        {
            return db.Delete<TestGen.MariaDB.Data.Sale>(string.Format("Sale_Id={0}", _SaleId));
        }

        // ParentRelations
        public static TestGen.MariaDB.Data.Customer Select_Parent_Customer(Database db, Int32 _CustomerId)
        {
            return db.SelectSingle<Customer>(string.Format("Customer_Id={0}", _CustomerId));
        }
        public static TestGen.MariaDB.Data.Customer Select_Parent_Customer(Database db, TestGen.MariaDB.Data.Sale rec)
        {
            return Select_Parent_Customer(db, rec.SaleCustomerId);
        }

        // ChildRelations
        public static List<TestGen.MariaDB.Data.Saledetail> Select_Children_Saledetail(Database db, Int32 _DetSaleId)
        {
            return db.Select<Saledetail>(string.Format("Det_Sale_Id={0}", _DetSaleId));
        }

        public static List<TestGen.MariaDB.Data.Saledetail> Select_Children_Saledetail(Database db, TestGen.MariaDB.Data.Sale rec)
        {
            return Select_Children_Saledetail(db, rec.SaleId);
        }

    }

}
