// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.MariaDB.Data;

namespace TestGen.MariaDB.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_SaleDetail : BLClass<TestGen.MariaDB.Data.Saledetail>
    {

        public static TestGen.MariaDB.Data.Saledetail SelectByPk(Database db, Int32 _DetailId)
        {
            return db.SelectSingle<TestGen.MariaDB.Data.Saledetail>(string.Format("Detail_Id={0}", _DetailId));
        }

        public static int DeleteByPk(Database db, Int32 _DetailId)
        {
            return db.Delete<TestGen.MariaDB.Data.Saledetail>(string.Format("Detail_Id={0}", _DetailId));
        }

        // ParentRelations
        public static TestGen.MariaDB.Data.Sale Select_Parent_Sale(Database db, Int32 _SaleId)
        {
            return db.SelectSingle<Sale>(string.Format("Sale_Id={0}", _SaleId));
        }
        public static TestGen.MariaDB.Data.Sale Select_Parent_Sale(Database db, TestGen.MariaDB.Data.Saledetail rec)
        {
            return Select_Parent_Sale(db, rec.DetSaleId);
        }


    }

}
