// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.MariaDB.Data;

namespace TestGen.MariaDB.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Vwsale : BLClass<TestGen.MariaDB.Data.Vwsale>
    {





    }

}
