// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel;
using Speed;
using Speed.Data;


namespace TestGen.Access.Data
{

    [DbTable("", "SaleDetail")]
    [Serializable]
    [DataContract(Name = "SaleDetail", Namespace = "")]
//    [System.Diagnostics.DebuggerStepThrough]
    public partial class SaleDetail : Record, ICloneable, INotifyPropertyChanged
    {

        private Int32 z_DetSaleId;
        [DbColumn("DetSaleId")]
        [DataMember]
        public Int32 DetSaleId
        {
            get { return z_DetSaleId; }
            set
            {
                if (z_DetSaleId != value)
                {
                    z_DetSaleId = value;
                    this.RaisePropertyChanged("DetSaleId");
                }
            }
        }

        private Int32 z_DetailId;
        [DbColumn("DetailId")]
        [DataMember]
        public Int32 DetailId
        {
            get { return z_DetailId; }
            set
            {
                if (z_DetailId != value)
                {
                    z_DetailId = value;
                    this.RaisePropertyChanged("DetailId");
                }
            }
        }

        
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region IsEqual

        public bool IsEqual(SaleDetail value)
        {
            if (value == null)
                return false;
            return
				this.DetSaleId == value.DetSaleId &&
				this.DetailId == value.DetailId;

        }

        #endregion IsEqual

        #region Clone

        public override object Clone()
        {
            return CloneT();
        }

        public SaleDetail CloneT()
        {
            SaleDetail value = new SaleDetail();
            value.RecordStatus = this.RecordStatus;
            value.RecordTag = this.RecordTag;

			value.DetSaleId = this.DetSaleId;
			value.DetailId = this.DetailId;

            return value;
        }

        #endregion Clone

        #region Create

        public static SaleDetail Create(Int32 _DetSaleId)
        {
            SaleDetail __value = new SaleDetail();

			__value.DetSaleId = _DetSaleId;

            return __value;
        }

        #endregion Create

   }

}
