// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.Oracle.Data;

namespace TestGen.Oracle.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Customer : BLClass<TestGen.Oracle.Data.Customer>
    {

        public static TestGen.Oracle.Data.Customer SelectByPk(Database db, Decimal _CustomerId)
        {
            return db.SelectSingle<TestGen.Oracle.Data.Customer>(string.Format("CUSTOMER_ID={0}", _CustomerId));
        }

        public static int DeleteByPk(Database db, Decimal _CustomerId)
        {
            return db.Delete<TestGen.Oracle.Data.Customer>(string.Format("CUSTOMER_ID={0}", _CustomerId));
        }


        // ChildRelations
        public static List<TestGen.Oracle.Data.Sale> Select_Children_Sale(Database db, Decimal _SaleCustomerId)
        {
            return db.Select<Sale>(string.Format("SALE_CUSTOMER_ID={0}", _SaleCustomerId));
        }

        public static List<TestGen.Oracle.Data.Sale> Select_Children_Sale(Database db, TestGen.Oracle.Data.Customer rec)
        {
            return Select_Children_Sale(db, rec.CustomerId);
        }

    }

}
