// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.Access.Data;

namespace TestGen.Access.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_SaleDetail : BLClass<TestGen.Access.Data.SaleDetail>
    {

        public static TestGen.Access.Data.SaleDetail SelectByPk(Database db, Int32 _DetailId, Int32 _DetSaleId)
        {
            return db.SelectSingle<TestGen.Access.Data.SaleDetail>(string.Format("DetailId={0} AND DetSaleId={1}", _DetailId, _DetSaleId));
        }

        public static int DeleteByPk(Database db, Int32 _DetailId, Int32 _DetSaleId)
        {
            return db.Delete<TestGen.Access.Data.SaleDetail>(string.Format("DetailId={0} AND DetSaleId={1}", _DetailId, _DetSaleId));
        }



    }

}
