// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.Firebird.Data;

namespace TestGen.Firebird.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Customer : BLClass<TestGen.Firebird.Data.Customer>
    {

        public static TestGen.Firebird.Data.Customer SelectByPk(Database db, Int32 _CustomerId)
        {
            return db.SelectSingle<TestGen.Firebird.Data.Customer>(string.Format("CUSTOMER_ID={0}", _CustomerId));
        }

        public static int DeleteByPk(Database db, Int32 _CustomerId)
        {
            return db.Delete<TestGen.Firebird.Data.Customer>(string.Format("CUSTOMER_ID={0}", _CustomerId));
        }



    }

}
