// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.Firebird.Data;

namespace TestGen.Firebird.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Sale : BLClass<TestGen.Firebird.Data.Sale>
    {

        public static TestGen.Firebird.Data.Sale SelectByPk(Database db, Int32 _SaleId)
        {
            return db.SelectSingle<TestGen.Firebird.Data.Sale>(string.Format("SALE_ID={0}", _SaleId));
        }

        public static int DeleteByPk(Database db, Int32 _SaleId)
        {
            return db.Delete<TestGen.Firebird.Data.Sale>(string.Format("SALE_ID={0}", _SaleId));
        }

        // ParentRelations
        public static TestGen.Firebird.Data.Customer Select_Parent_Customer(Database db, Int32 _CustomerId)
        {
            return db.SelectSingle<Customer>(string.Format("CUSTOMER_ID={0}", _CustomerId));
        }
        public static TestGen.Firebird.Data.Customer Select_Parent_Customer(Database db, TestGen.Firebird.Data.Sale rec)
        {
            return Select_Parent_Customer(db, rec.SaleCustomerId);
        }


    }

}
