// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.Firebird.Data;

namespace TestGen.Firebird.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Sales : BLClass<TestGen.Firebird.Data.Sales>
    {

        public static TestGen.Firebird.Data.Sales SelectByPk(Database db, Int32 _Testperfid)
        {
            return db.SelectSingle<TestGen.Firebird.Data.Sales>(string.Format("TESTPERFID={0}", _Testperfid));
        }

        public static int DeleteByPk(Database db, Int32 _Testperfid)
        {
            return db.Delete<TestGen.Firebird.Data.Sales>(string.Format("TESTPERFID={0}", _Testperfid));
        }



    }

}
