// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.MySql.Data;

namespace TestGen.MySql.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Customer : BLClass<TestGen.MySql.Data.Customer>
    {

        public static TestGen.MySql.Data.Customer SelectByPk(Database db, Int32 _CustomerId)
        {
            return db.SelectSingle<TestGen.MySql.Data.Customer>(string.Format("Customer_Id={0}", _CustomerId));
        }

        public static int DeleteByPk(Database db, Int32 _CustomerId)
        {
            return db.Delete<TestGen.MySql.Data.Customer>(string.Format("Customer_Id={0}", _CustomerId));
        }


        // ChildRelations
        public static List<TestGen.MySql.Data.Sale> Select_Children_Sale(Database db, Int32 _SaleCustomerId)
        {
            return db.Select<Sale>(string.Format("Sale_Customer_Id={0}", _SaleCustomerId));
        }

        public static List<TestGen.MySql.Data.Sale> Select_Children_Sale(Database db, TestGen.MySql.Data.Customer rec)
        {
            return Select_Children_Sale(db, rec.CustomerId);
        }

    }

}
