// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TesteRaizen.Data;

namespace TesteRaizen.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_CepCidades : BLClass<TesteRaizen.Data.CepCidades>
    {

        public static TesteRaizen.Data.CepCidades SelectByPk(Database db, Int32 _IdCidade)
        {
            return db.SelectSingle<TesteRaizen.Data.CepCidades>(string.Format("IdCidade={0}", _IdCidade));
        }

        public static int DeleteByPk(Database db, Int32 _IdCidade)
        {
            return db.Delete<TesteRaizen.Data.CepCidades>(string.Format("IdCidade={0}", _IdCidade));
        }



    }

}
