// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TesteRaizen.Data;

namespace TesteRaizen.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_CepEstados : BLClass<TesteRaizen.Data.CepEstados>
    {

        public static TesteRaizen.Data.CepEstados SelectByPk(Database db, String _UF)
        {
            return db.SelectSingle<TesteRaizen.Data.CepEstados>(string.Format("UF={0}", Q(_UF)));
        }

        public static int DeleteByPk(Database db, String _UF)
        {
            return db.Delete<TesteRaizen.Data.CepEstados>(string.Format("UF={0}", Q(_UF)));
        }



    }

}
