// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TesteRaizen.Data;

namespace TesteRaizen.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_EstadoCivil : BLClass<TesteRaizen.Data.EstadoCivil>
    {

        public static TesteRaizen.Data.EstadoCivil SelectByPk(Database db, Int32 _IdEstadoCivil)
        {
            return db.SelectSingle<TesteRaizen.Data.EstadoCivil>(string.Format("IdEstadoCivil={0}", _IdEstadoCivil));
        }

        public static int DeleteByPk(Database db, Int32 _IdEstadoCivil)
        {
            return db.Delete<TesteRaizen.Data.EstadoCivil>(string.Format("IdEstadoCivil={0}", _IdEstadoCivil));
        }


        // ChildRelations
        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, Int32 _IdEstadoCivil)
        {
            return db.Select<PessoaFisica>(string.Format("IdEstadoCivil={0}", _IdEstadoCivil));
        }

        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, TesteRaizen.Data.EstadoCivil rec)
        {
            return Select_Children_PessoaFisica(db, rec.IdEstadoCivil);
        }

    }

}
