// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TesteRaizen.Data;

namespace TesteRaizen.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Nacionalidade : BLClass<TesteRaizen.Data.Nacionalidade>
    {

        public static TesteRaizen.Data.Nacionalidade SelectByPk(Database db, Int32 _IdNacionalidade)
        {
            return db.SelectSingle<TesteRaizen.Data.Nacionalidade>(string.Format("IdNacionalidade={0}", _IdNacionalidade));
        }

        public static int DeleteByPk(Database db, Int32 _IdNacionalidade)
        {
            return db.Delete<TesteRaizen.Data.Nacionalidade>(string.Format("IdNacionalidade={0}", _IdNacionalidade));
        }


        // ChildRelations
        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, Int32 _Nacionalidade)
        {
            return db.Select<PessoaFisica>(string.Format("Nacionalidade={0}", _Nacionalidade));
        }

        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, TesteRaizen.Data.Nacionalidade rec)
        {
            return Select_Children_PessoaFisica(db, rec.IdNacionalidade);
        }

    }

}
