// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TesteRaizen.Data;

namespace TesteRaizen.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_PessoaFisica : BLClass<TesteRaizen.Data.PessoaFisica>
    {

        public static TesteRaizen.Data.PessoaFisica SelectByPk(Database db, Int32 _IdPessoa)
        {
            return db.SelectSingle<TesteRaizen.Data.PessoaFisica>(string.Format("IdPessoa={0}", _IdPessoa));
        }

        public static int DeleteByPk(Database db, Int32 _IdPessoa)
        {
            return db.Delete<TesteRaizen.Data.PessoaFisica>(string.Format("IdPessoa={0}", _IdPessoa));
        }

        // ParentRelations
        public static TesteRaizen.Data.EstadoCivil Select_Parent_EstadoCivil(Database db, Int32 _IdEstadoCivil)
        {
            return db.SelectSingle<EstadoCivil>(string.Format("IdEstadoCivil={0}", _IdEstadoCivil));
        }
        public static TesteRaizen.Data.EstadoCivil Select_Parent_EstadoCivil(Database db, TesteRaizen.Data.PessoaFisica rec)
        {
            return Select_Parent_EstadoCivil(db, rec.IdEstadoCivil);
        }

        public static TesteRaizen.Data.PessoaFisica Select_Parent_PessoaFisica(Database db, Int32? _IdPessoaConjugue)
        {
            return db.SelectSingle<PessoaFisica>(string.Format("IdPessoa={0}", _IdPessoaConjugue));
        }
        public static TesteRaizen.Data.PessoaFisica Select_Parent_PessoaFisica(Database db, TesteRaizen.Data.PessoaFisica rec)
        {
            return Select_Parent_PessoaFisica(db, rec.IdPessoaConjugue);
        }

        public static TesteRaizen.Data.Nacionalidade Select_Parent_Nacionalidade(Database db, Int32 _IdNacionalidade)
        {
            return db.SelectSingle<Nacionalidade>(string.Format("IdNacionalidade={0}", _IdNacionalidade));
        }
        public static TesteRaizen.Data.Nacionalidade Select_Parent_Nacionalidade(Database db, TesteRaizen.Data.PessoaFisica rec)
        {
            return Select_Parent_Nacionalidade(db, rec.Nacionalidade);
        }

        // ChildRelations
        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, Int32 _IdPessoaConjugue)
        {
            return db.Select<PessoaFisica>(string.Format("IdPessoaConjugue={0}", _IdPessoaConjugue));
        }

        public static List<TesteRaizen.Data.PessoaFisica> Select_Children_PessoaFisica(Database db, TesteRaizen.Data.PessoaFisica rec)
        {
            return Select_Children_PessoaFisica(db, rec.IdPessoa);
        }

    }

}
