// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.SqlLite.Data;

namespace TestGen.SqlLite.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_Sale : BLClass<TestGen.SqlLite.Data.Sale>
    {

        public static TestGen.SqlLite.Data.Sale SelectByPk(Database db, Int64 _SaleId)
        {
            return db.SelectSingle<TestGen.SqlLite.Data.Sale>(string.Format("SaleId={0}", _SaleId));
        }

        public static int DeleteByPk(Database db, Int64 _SaleId)
        {
            return db.Delete<TestGen.SqlLite.Data.Sale>(string.Format("SaleId={0}", _SaleId));
        }

        // ParentRelations
        public static TestGen.SqlLite.Data.Customer Select_Parent_Customer(Database db, Int64? _CustomerId)
        {
            return db.SelectSingle<Customer>(string.Format("CustomerId={0}", _CustomerId));
        }
        public static TestGen.SqlLite.Data.Customer Select_Parent_Customer(Database db, TestGen.SqlLite.Data.Sale rec)
        {
            return Select_Parent_Customer(db, rec.SaleCustomerId);
        }

        // ChildRelations
        public static List<TestGen.SqlLite.Data.SaleDetail> Select_Children_SaleDetail(Database db, Int64 _DetSaleId)
        {
            return db.Select<SaleDetail>(string.Format("DetSaleId={0}", _DetSaleId));
        }

        public static List<TestGen.SqlLite.Data.SaleDetail> Select_Children_SaleDetail(Database db, TestGen.SqlLite.Data.Sale rec)
        {
            return Select_Children_SaleDetail(db, rec.SaleId);
        }

    }

}
