// ****** SPEED ******
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Speed.Data;
using TestGen.SqlLite.Data;

namespace TestGen.SqlLite.BL
{

    //[System.Diagnostics.DebuggerStepThrough]
    public partial class BL_SaleDetail : BLClass<TestGen.SqlLite.Data.SaleDetail>
    {

        public static TestGen.SqlLite.Data.SaleDetail SelectByPk(Database db, Int64 _DetailId)
        {
            return db.SelectSingle<TestGen.SqlLite.Data.SaleDetail>(string.Format("DetailId={0}", _DetailId));
        }

        public static int DeleteByPk(Database db, Int64 _DetailId)
        {
            return db.Delete<TestGen.SqlLite.Data.SaleDetail>(string.Format("DetailId={0}", _DetailId));
        }

        // ParentRelations
        public static TestGen.SqlLite.Data.Sale Select_Parent_Sale(Database db, Int64? _SaleId)
        {
            return db.SelectSingle<Sale>(string.Format("SaleId={0}", _SaleId));
        }
        public static TestGen.SqlLite.Data.Sale Select_Parent_Sale(Database db, TestGen.SqlLite.Data.SaleDetail rec)
        {
            return Select_Parent_Sale(db, rec.DetSaleId);
        }


    }

}
